{"trial_id": "08", "hyperparameters": {"space": [{"class_name": "Float", "config": {"name": "dropout_rate", "default": 0.3, "conditions": [], "min_value": 0.2, "max_value": 0.5, "step": 0.05, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "l2_factor", "default": 0.0001, "conditions": [], "values": [0.0001, 0.0005, 0.001], "ordered": true}}, {"class_name": "Int", "config": {"name": "n_layers_to_unfreeze", "default": 10, "conditions": [], "min_value": 10, "max_value": 100, "step": 5, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "learning_rate", "default": 0.0001, "conditions": [], "min_value": 0.0001, "max_value": 0.01, "step": null, "sampling": "log"}}], "values": {"dropout_rate": 0.30000000000000004, "l2_factor": 0.001, "n_layers_to_unfreeze": 90, "learning_rate": 0.008921950463194462}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/tensorflow/python/eager/execute.py\", line 59, in quick_execute\n    except TypeError as e:\ntensorflow.python.framework.errors_impl.ResourceExhaustedError: Graph execution error:\n\nDetected at node StatefulPartitionedCall defined at (most recent call last):\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/src/training/train_resnet2.py\", line 135, in <module>\n\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 234, in search\n\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 274, in _try_run_and_update_trial\n\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras_tuner/src/engine/base_tuner.py\", line 239, in _run_and_update_trial\n\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 371, in fit\n\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 219, in function\n\n  File \"/home/czegarra/proyectoDeep/DeepLearning_Project/env/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 132, in multi_step_on_iterator\n\nOut of memory while trying to allocate 1319344096 bytes.\n\t [[{{node StatefulPartitionedCall}}]]\nHint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.\n [Op:__inference_multi_step_on_iterator_2369217]\n"}